### ISSUE TITLE
Abp widget generator 

### ISSUE THREAD

**Issue by suhaib-mousa** [carbonhe/abp-insight#1]
Currently, ABP widgets require manual configuration, which involves setting up the widget name, controller route, scripts, styles, and initialization behavior. This process can be repetitive and time-consuming.

Proposed Feature:

Add a Widget Configuration Wizard to make it easier to create and set up widgets. The wizard could allow developers to:
	•	Enter the widget name.
	•	Specify the controller route (if needed).
	•	Add scripts and styles.
	•	Choose whether the widget should auto-initialize.
	•	Provide additional options for custom settings.

Why It’s Useful:
	•	Saves time by automating repetitive tasks.
	•	Reduces mistakes in widget setup.
	•	Makes it easier for new developers to work with widgets in ABP.

**Comment by suhaib-mousa** [comment]
I would love to contribute to implementing this feature. Please let me know how I can assist.

**Comment by carbonhe** [comment]
@suhaib-mousa  That sounds like a very practical idea. But I have no experience related to `Abp Widget`(I work on development of front-end and back-end separation all the time),so  I think I need to understand this first.


> I would love to contribute to implementing this feature. Please let me know how I can assist.

If you are familiar with Rider plugin development, you can summit a PR for implementing this. Or  You can provide me with some more detailed suggestions regarding the feature.

**Comment by suhaib-mousa** [comment]
> @suhaib-mousa That sounds like a very practical idea. But I have no experience related to `Abp Widget`(I work on development of front-end and back-end separation all the time),so I think I need to understand this first.
> 
> > I would love to contribute to implementing this feature. Please let me know how I can assist.
> 
> If you are familiar with Rider plugin development, you can summit a PR for implementing this. Or You can provide me with some more detailed suggestions regarding the feature.

I’ll investigate further into how this can be implemented and then submit a PR.

**Comment by suhaib-mousa** [comment]
@carbonhe, If you could provide me with the steps to install the plugin directly from the repo code (not the marketplace), it would be very helpful for me.

**Comment by carbonhe** [comment]
@suhaib-mousa  I added a `How to run` [selection](https://github.com/carbonhe/abp-insight?tab=readme-ov-file#how-to-run) to the READM.md,  you can follow it to debug. If you have any questions, please feel free to contact me at any time.

**Comment by suhaib-mousa** [comment]
> @suhaib-mousa I added a `How to run` [selection](https://github.com/carbonhe/abp-insight?tab=readme-ov-file#how-to-run) to the READM.md, you can follow it to debug. If you have any questions, please feel free to contact me at any time.

Hi @carbonhe,

I think it would be great if you could set up the creation option and add some TODOs so I can continue the development. I don’t have much experience with Rider plugin development, and it seems like the documentation is still lacking since it’s in the early stages.

Here’s what we need:

- Set up the menu action `Generate Abp Widget` in the Add submenu.

![image](https://github.com/user-attachments/assets/07268a9a-9966-4761-9806-6a389d66e6b9)

- Add steps or comments in the code to guide me on what to do next.

Thanks in advance!

**Comment by carbonhe** [comment]
@suhaib-mousa Okay, I will tell you when I have any progress.

**Comment by suhaib-mousa** [comment]
> @suhaib-mousa Okay, I will tell you when I have any progress.

@carbonhe, any updates?

**Comment by carbonhe** [comment]
> > @suhaib-mousa Okay, I will tell you when I have any progress.
> 
> @carbonhe, any updates?

@suhaib-mousa I created `feature/abp_widget_generator` branch and finished some basic implementation for [FileTemplate](https://www.jetbrains.com/help/resharper/sdk/LiveTemplates.html), we can create a simple AbpWidget class so far. But this is not enough for our needs, we can do nothing except input a name, this is the default behavior of the resharper platform and we can't change it.
So, I think that will be a challenge. I'm looking for another way to implement the generator and testing in my local repo.

Back to the generator, I want to confirm these things：
- How many file will be generated? Only the widget class?
- Do I need to perform semantic analysis on other files when generating?

![image](https://github.com/user-attachments/assets/365100ab-5a75-4e39-ad0f-bb9fb3eeec05)
![image](https://github.com/user-attachments/assets/2dac2d36-3a05-4168-80a7-43bf593703da)

**Comment by suhaib-mousa** [comment]
> > > @suhaib-mousa Okay, I will tell you when I have any progress.
> > 
> > 
> > @carbonhe, any updates?
> 
> @suhaib-mousa I created `feature/abp_widget_generator` branch and finished some basic implementation for [FileTemplate](https://www.jetbrains.com/help/resharper/sdk/LiveTemplates.html), we can create a simple AbpWidget class so far. But this is not enough for our needs, we can do nothing except input a name, this is the default behavior of the resharper platform and we can't change it. So, I think that will be a challenge. I'm looking for another way to implement the generator and testing in my local repo.
> 
> Back to the generator, I want to confirm these things：
> 
> * How many file will be generated? Only the widget class?
> * Do I need to perform semantic analysis on other files when generating?
> 
> ![image](https://private-user-images.githubusercontent.com/37563160/389828326-365100ab-5a75-4e39-ad0f-bb9fb3eeec05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MDYwOTcsIm5iZiI6MTczMjYwNTc5NywicGF0aCI6Ii8zNzU2MzE2MC8zODk4MjgzMjYtMzY1MTAwYWItNWE3NS00ZTM5LWFkMGYtYmI5ZmIzZWVlYzA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDA3MjMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkMjhiYjcxNTFhZDdkMWI2NDhmYjIwYjhhNWEyZTEyMDJiNjdmNTNiOWQxNTUwZGYxODlhNGE1Y2FlYTNiMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tqGFanjKSTsnLs6AAeN8K5FsCP_s_lEF8PP2m_WcxRU) ![image](https://private-user-images.githubusercontent.com/37563160/389829509-2dac2d36-3a05-4168-80a7-43bf593703da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MDYwOTcsIm5iZiI6MTczMjYwNTc5NywicGF0aCI6Ii8zNzU2MzE2MC8zODk4Mjk1MDktMmRhYzJkMzYtM2EwNS00MTY4LTgwYTctNDNiZjU5MzcwM2RhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI2VDA3MjMxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlZjA3MTEyNDM4MGNmZTEyYTQyZTlmNDRmOTFiZDk1YzMzYzI3MzRjMTFkZDRmNTEzMjBhZTlkMmZlZDQzNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6GsbIFGUFueH3twsEHvISaygEGUMfJUvJfhrwU9-7ug)


It depends on what the end user needs to generate.

From a broader perspective, I think we should allow the user to at least provide the name of the widget. Additionally, if they want to include scripts, they should be able to specify the script and style paths, along with the controller path if required.

I suggest starting with a simple example to demonstrate this functionality, and I can build on it further from there.

**Comment by carbonhe** [comment]
> I suggest starting with a simple example to demonstrate this functionality, and I can build on it further from there.

@suhaib-mousa All right, I'm still working at the beginning steps of the new implementation.

**Comment by carbonhe** [comment]
@suhaib-mousa I have completed the starting work in `feature/abp_widget_generator` branch, it should now be possible to implement all the features we discussed earlier. 
There are a couple of tasks you can continue to develop:
- complete the "Generate Abp widge" dialog which user interact with.
- If it is necessary to generate multiple files, complete the generating logic and write the template file. 

I have left TODO comments in places where further work is needed.

**Comment by carbonhe** [comment]
@suhaib-mousa  Are you still developing with this?

**Comment by suhaib-mousa** [comment]
> @suhaib-mousa Are you still developing with this?

Hi @carbonhe ,

Apologies for the delay in addressing this issue. I’ve recently transitioned to a new position at another company, which has affected my availability. 

I’ll provide ASAP clear instructions and details on how to implement the remaining features to ensure it can be completed without waiting further. Thank you for your patience and understanding!

**Comment by carbonhe** [comment]
Hi @suhaib-mousa ,
After several days of investigation, I think it's unnecessary to provide a configuration wizard, because this workflow is actually not complicated, It's just  modify  the widget attribute's properties. So I think the more intuitive way in this scenario is to directly modify the source code, we can do more things in `CODING` stage instead of `CREATING` stage. 
I will reimplement it according to the following steps:
1. Generate the simple widget class by given name, the class just extends `AbpViewComponent` and attributed with `WidgetAttribute`.
2. Provides code completion for  styles/scripts 's  path  according the project context. 
3. Genrate the cshtml file  according the view name if needed. (Rider has implemented this feature)

Do you think this plan is feasible?

**Comment by suhaib-mousa** [comment]
> Hi @suhaib-mousa , After several days of investigation, I think it's unnecessary to provide a configuration wizard, because this workflow is actually not complicated, It's just modify the widget attribute's properties. So I think the more intuitive way in this scenario is to directly modify the source code, we can do more things in `CODING` stage instead of `CREATING` stage. I will reimplement it according to the following steps:
> 
> 1. Generate the simple widget class by given name, the class just extends `AbpViewComponent` and attributed with `WidgetAttribute`.
> 2. Provides code completion for  styles/scripts 's  path  according the project context.
> 3. Genrate the cshtml file  according the view name if needed. (Rider has implemented this feature)
> 
> Do you think this plan is feasible?

That sounds great! We can work on it further when I'm available.
